### ISSUE TITLE
Build difficulty

### ISSUE THREAD

**Issue by dalb8** [gmcnew/pax#2]
I can't get it to build. Using platform tools 14. Error is like this:

   [echo] Handling RenderScript files...
[renderscript] No RenderScript files to compile.
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [aapt] res/raw/explode_factory.wav:0: error: Resource entry explode_factory is already defined.
     [aapt] res/raw/explode_factory.ogg:0: Originally defined here.
==== stdout end ====
==== stderr begin ====
BUILD FAILED
/home/gerry/android-sdk-linux/tools/ant/build.xml:621: The following error occurred while executing this line:
/home/gerry/android-sdk-linux/tools/ant/build.xml:657: null returned: 1

Total time: 2 seconds
==== stderr end ====

**Comment by dalb8** [comment]
I removed explode_factory.ogg and it builds

**Comment by dalb8** [comment]
Not really sure how to play it finally :-(

**Comment by gmcnew** [comment]
Yeah, I really need to add some kind of simple tutorial or help text.

Just out of curiosity, what were you able to figure out on your own? What was most confusing?

**Comment by dalb8** [comment]
No matter what I press on the screen, it seems like nothing makes any difference. I'm not familiar with the original.

**Comment by gmcnew** [comment]
When your screen-presses have no effect, what's actually on the screen? The intro screen (which says "Pax")? Or the game screen, where the big ships are slowly circling each other?

**Comment by dalb8** [comment]
Sorry, I was unclear. I can press buttons at the bottom to launch things, but they have a life of their own, so the tactical element of the game seems weak.

**Comment by gmcnew** [comment]
Yep, this is intended (and something that will be explained in the future). It's how the original game works, too -- you try to beat your opponent by building the correct type of ships, but the ships themselves are on autopilot. Each ship type has a prioritized list of ship types to attack.

Getting rid of autopilot and making the player pilot dozens of ships through a touch screen in a fast-paced two-player game would probably be extremely difficult.

If the game is too easy, try changing the AI difficulty level. If the highest difficulty is still too easy, let me know. =)
